### ISSUE TITLE
Never Re-download Dependencies

### ISSUE THREAD

**Issue by JoelLogan** [PercentBoat4164/Illumination-Engine#21]
If the dependencies are already saved in the correct location on the drive, they should not be re-downloaded.

**Comment by JoelLogan** [comment]
The local dependencies should also be version checked to see if they are valid.

**Comment by PercentBoat4164** [comment]
@JoelLogan, I added some basic checks for dependency versions on a local instance of this branch, but I don't believe that it is possible for this to work with all of the dependencies. For example GLEW's version is tracked as a link to the location from which it is downloaded. This means that the version number given by the package will never match the version stored locally, and specified in the dependencies list. I could implement the solution that I have anyway and come up with a work around for dependencies like that, or I could leave it as is. A workaround would consist of something that essentially prevents version checking for that package thereby allowing the use of any version, even ones that do not match the given version string, or are known not to work. What do you think is the best solution going forward?
